#!/usr/bin/env python3

from publications import publications

# publications_src = "<table>" + "\n".join(
#     publication.to_html_table() for publication in publications
# ) + "</table>"

publications_src = "\n".join(
    publication.to_html_simple(one_line=False, long_venue=False)
    for publication in publications
)

with open("template.html") as f:
    doc = "".join(f.readlines())
    doc = doc.replace("PUBLICATIONS", publications_src)
    src = f"""<!-- Generated by compile.py -->\n{doc}"""
    print(src)